name: Generate Resource Packs
on:
  push:
    branches:
      - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build Vanilla
        uses: Sorrowfall/Resource-Packager@main
        with:
          parts:
            shared/
            vanilla/
          name: Pack-Vanilla
      - name: Create Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ github.event.head_commit.message }}
          tag: test
          gzip: false
          files: >
            build/Pack-Vanilla.zip
